name: Publish npm package

on:
    push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 g++ make build-essential

      - name: Use correct Python version
        run: |
          sudo ln -sf /usr/bin/python3 /usr/bin/python

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}